// win
export const SET_WIN_BOUNDS = 'CTOOLS_SET_WIN_BOUNDS';
export const SET_WIN_HEIGHT = 'CTOOLS_SET_WIN_HEIGHT';
export const SET_WIN_VISIABLE = 'CTOOLS_SET_WIN_VISIABLE';
export const OPEN_PREFERENCE = 'CTOOLS_OPEN_PREFERENCE';

// source
export const SEARCH_APPLICATIONS = 'CTOOLS_SEARCH_APPLICATIONS';
export const SEARCH_FEATURES = 'CTOOLS_SEARCH_FEATURES';
export const SELECT_FEATURE = 'CTOOLS_SELECT_FEATURE';