// win
export const SET_WIN_BOUNDS = 'CTOOLS_SET_WIN_BOUNDS';
export const SET_WIN_HEIGHT = 'CTOOLS_SET_WIN_HEIGHT';
export const SET_WIN_VISIABLE = 'CTOOLS_SET_WIN_VISIABLE';
export const OPEN_PREFERENCE = 'CTOOLS_OPEN_PREFERENCE';
export const LOAD_PLUGIN_MAIN = 'CTOOLS_LOAD_PLUGIN_MAIN';

// source
export const SEARCH_APPLICATIONS = 'CTOOLS_SEARCH_APPLICATIONS';
export const SEARCH_FEATURES = 'CTOOLS_SEARCH_FEATURES';
/**
 * 渲染进程选择了插件的功能，通知主进程
 */
export const SELECT_FEATURE = 'CTOOLS_SELECT_FEATURE';
export const SEARCH_PLUGIN_FEATURE = 'CTOOLS_SELECT_PLUGIN_FEATURE';

/**
 * 主进程通知渲染进程打开插件主页面
 */
export const OPEN_PLUGIN_MAIN = 'CTOOLS_OPEN_PLUGIN_MAIN';